### PR TITLE
App Size Optimized by replacing PNG's with WebP

### PR DESCRIPTION
**Pull request by way2jatin**
screen shot 2017-05-08 at 10 02 21 pm

App Size dropped to 1.6 MB on generating a production build. Check the screenshot above for the same.

Ciao

### CODE REVIEW

**Comment by webianks** [comment]
What is the purpose of putting this:  resConfigs "en" ?

**Comment by way2jatin** [comment]
@webianks As far as i saw the app , it is currently supporting only English as a language . So resConfigs actually loads only English as a language for all the dependencies thus saving a lot of overhead.

**Comment by webianks** [comment]
Does it effect the resource string translation as we have provided translations for other locales?

**Comment by way2jatin** [comment]
Just added languages which are currently being supported in the app.

**Comment by webianks** [comment]
That's better. 👍

**Comment by webianks** [comment]
Also we will check how many users we will loose by upgrading the minimum api to 18 then I will accept to take WebP as drawable images format.

**Comment by way2jatin** [comment]
Sure no problem.

**Pull request merged**
