### PR TITLE
final

### PR DESCRIPTION
**Pull request by salRoid**
yo bro thanks

### CODE REVIEW

**Comment by salRoid** [comment]
u r awesome

**Comment by salRoid** [comment]
@webianks thanks bro

**Comment by webianks** [comment]
@salRoid No problem anything for the development RIP #talkers #blah #blah

**Comment by salRoid** [comment]
- Updated Share Activity
- Search Activity
@webianks

**Comment by webianks** [comment]
# Okay I will do that # surely..

**Comment by salRoid** [comment]
`  youtube_link = (ImageView) findViewById(R.id.detail_youtube);
        banner = (ImageView) findViewById(R.id.bannu);`

**Comment by webianks** [comment]
Wrong naming bro #bannu Seriously?

**Comment by salRoid** [comment]
screenshot_2016-07-22-23-21-21

**Comment by webianks** [comment]
Awesomness#

**Comment by salRoid** [comment]
[www.salroid.tech](url)

**Pull request merged**
